# Generated by Django 5.1.5 on 2025-03-20 12:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('date_cours', models.DateField()),
                ('description', models.TextField()),
                ('date_publication', models.DateField(default=datetime.date.today)),
                ('heure', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.TextField(max_length=200, null=True)),
                ('niveau', models.CharField(max_length=800, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('duree', models.CharField(max_length=20)),
                ('nombre', models.IntegerField(null=True)),
                ('localisation', models.CharField(default='FIDALLI', max_length=200)),
                ('resume', models.TextField(null=True)),
                ('description', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=200)),
                ('date_formation', models.DateField(default=datetime.date(2024, 1, 20))),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField(null=True)),
                ('statut', models.CharField(choices=[('confirmé', 'confirmé'), ('annulé', 'annulé'), ('attente', 'attente')], default='attente', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AffectationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.group')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('phone_number', models.TextField(default='', max_length=20)),
                ('domaine_etude', models.TextField(default='', max_length=40)),
                ('niveau_etude', models.TextField(default='', max_length=100)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation')),
            ],
        ),
    ]
