# Generated by Django 5.1.5 on 2025-03-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formation', '0002_initial'),
        ('programmeTalent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectationstage',
            name='inscrit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.inscrit'),
        ),
        migrations.AddField(
            model_name='moduleformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
        migrations.AddField(
            model_name='moduleformation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.AddField(
            model_name='seance',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
        migrations.AddField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.AddField(
            model_name='seance',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscrit',
            unique_together={('formation', 'user')},
        ),
    ]
