# Generated by Django 4.2.19 on 2025-03-18 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programmeTalent', '0003_remove_seance_user_seance_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance_users',
            name='user',
        ),
        migrations.AddField(
            model_name='seance',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seance_users',
            name='customuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
