# Generated by Django 4.2.19 on 2025-03-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0004_remove_seance_users_user_seance_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seance_users',
        ),
    ]
