# Generated by Django 5.1.5 on 2025-03-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(default='', max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('startDateTime', models.DateTimeField(null=True)),
                ('duree', models.IntegerField(null=True)),
                ('webinarUrl', models.URLField(blank=True, null=True)),
                ('maxParticipants', models.IntegerField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FuturAllies', 'FuturAllies'), ('Café des allies', 'Café des allies')], max_length=20, null=True)),
                ('updateDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=10, null=True)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('hasAcceptedTerms', models.BooleanField(default=False)),
                ('paymentStatus', models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('free', 'Free')], max_length=10, null=True)),
                ('paymentMethod', models.CharField(blank=True, choices=[('creditCard', 'Credit Card'), ('orangeMoney', 'Orange Money'), ('moovMoney', 'Moov Money'), ('sankMoney', 'Sank Money')], max_length=15, null=True)),
                ('isConfirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='', max_length=800)),
                ('cours', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_module', models.CharField(default='', max_length=800)),
                ('domaine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.domaine')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.TextField()),
                ('chapitre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', max_length=800)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_audio', models.TextField(default='', max_length=800)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_video', models.TextField(max_length=800)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section')),
            ],
        ),
    ]
