# Generated by Django 5.1.5 on 2025-03-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conferencier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinar',
            name='moderateurs',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='moderer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarenrollment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarenrollment',
            name='webinarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Formation.webinar'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarenrollment',
            unique_together={('webinarId', 'user')},
        ),
    ]
