# Generated by Django 4.2.19 on 2025-03-06 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webinarenrollment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarenrollment',
            name='webinarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Formation.webinar'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conferencier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinar',
            name='moderateurs',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='moderer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='module',
            name='domaine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.domaine'),
        ),
        migrations.AddField(
            model_name='cours',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
        migrations.AddField(
            model_name='contenu',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.cours'),
        ),
        migrations.AddField(
            model_name='audio',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.section'),
        ),
        migrations.AlterUniqueTogether(
            name='webinarenrollment',
            unique_together={('webinarId', 'user')},
        ),
    ]
