# Generated by Django 5.1.5 on 2025-03-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Formation', '0002_initial'),
        ('certificats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.certification'),
        ),
        migrations.AddField(
            model_name='coursusecertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_certifications', to='certificats.certification'),
        ),
        migrations.AddField(
            model_name='coursusecertification',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_courses', to='Formation.cours'),
        ),
        migrations.AddField(
            model_name='prerequisites',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.certification'),
        ),
        migrations.AddField(
            model_name='prerequisites',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='progression',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='progression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='certificats.question'),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponseUtilisateur', to='Formation.chapitre'),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='choix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificats.option'),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='certificats.question'),
        ),
        migrations.AddField(
            model_name='reponseutilisateur',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reponseutilisateur',
            unique_together={('user', 'question')},
        ),
    ]
